name: BitQuest
version: 2.0
author: The BitQuest Dev Team
main: com.bitquest.bitquest.BitQuest
description: The BitQuest Open Source Project
commands:
  banlist:
    description: "Prints the list of banned players"
    usage: "/banlist"
  butcher:
    description: "kills all entities in the current chunk"
    usage: "/butcher"
  clan:
    description: "used for creating, joining, operating clans"
    usage: "/clan <new|invite|kick|join|leave>"
  currency:
    description: "change player currency"
    usage: "/currency <ems|bits>"
  donate:
    description: "Donate to the server administrator using your wallet"
    usage: "/donate <amount>"
  home:
    description: "teleports you to your last bed"
    usage: "/home"
  land:
    description: "Manage permissions for the land you're standing on"
    usage: "/land <info|claim|transfer|permissions|price>"
  maintenance:
    description: "Enables maintenance mode and stops players from joining the server"
    usage: "/maintenance <seconds>"
  mod:
    description: "Utility to add/remove/list moderators"
    usage: "/mod <add|remove|list>"
  motd:
    description: "Change the message of the day"
    usage: "/motd <message>"
  pet:
    description: "Adopt an ocelot for 300 bits"
    usage: "/pet <name>"
  profession:
    description: "(EXPERIMENTAL) choose a profession"
    usage: "/profession rogue"
  send:
    description: "sends bits to other player"
    usage: "/send <amount> <player>"
  spawn:
    description: "teleports to spawn"
    usage: "/spawn"
  spectate:
    description: "Allows moderators to spectate players' actions"
    usage: "/spectate <player>"
  transfer:
    description: "Sends your BitQuest wallet balance to an external address of your own"
    usage: "/transfer <amount> <bitcoin address, e-mail or username>"
  trade:
    description: "Trade crypto for emeralds"
    usage: "/trade <amount>"
  unban:
    description: "Removes player from the ban list"
    usage: "/unban <player>"
  emergencystop:
    description: "Stops the server cleanly in case of emergency"
    usage: "/emergencystop [reason]"
  killAllVillagers:
    description: "Kills all the villagers"
    usage: "/killAllVillagers"
  upgradewallet:
    description: "Transfer funds from an old (BQ2.0) wallet"
    usage: "/upgradewallet"
  faucet:
    description: "Get testnet coins (development mode only)"
    usage: "/faucet"
  wallet:
    description: "Displays your BitQuest wallet info"
    usage: "/wallet"
  crashtest:
    description: "Crashes the plugin on purpose, hell breaks loose. Don't try this at home"
    usage: "/crashtest"
  report:
    description: "Sends a report message to the moderators"
    usage: "/report <player> <reason>"
  fixabandonland:
    description: "Fixes chunks with no owners that still have permissions"
    usage: "/fixabandonland [true|yes]"
  migrateclans:
    description: "Migrate clans to keep track of members"
    usage: "/migrateclans"
api-version: 1.16