name: BitQuest
version: 2.0
author: The BitQuest Dev Team
main: com.bitquest.bitquest.BitQuest
description: The BitQuest Open Source Project
commands:
  ban:
    description: "Adds player to the ban list"
    usage: "/ban <player>"
  banlist:
    description: "Prints the list of banned players"
    usage: "/banlist"
  clan:
    description: "used for creating, joining, operating clans"
    usage: "/clan <new|invite|kick|join|leave>"
  home:
    description: "teleport to your last bed"
    usage: "/home"
  transfer:
    description: "Sends your BitQuest wallet balance to an external address of your own"
    usage: "/transfer <amount> <bitcoin address or e-mail>"
  unban:
    description: "Removes player from the ban list"
    usage: "/unban <player>"
  spectate:
    description: "Allows moderators to spectate players' actions"
    usage: "/spectate <player>"
  mod:
    description: "Utility to add/remove/list moderators"
    usage: "/mod <add|remove|list>"
  land:
    description: "Claim or manage land plots"
    usage: "/land <claim|permission>"
  emergencystop:
    description: "Stops the server cleanly in case of emergency"
    usage: "/emergencystop [reason]"
  killAllVillagers:
    description: "Kills all the villagers"
    usage: "/killAllVillagers"
  faucet:
    description: "Get testnet coins (development mode only)"
    usage: "/faucet"
  wallet:
    description: "Displays your BitQuest wallet info"
    usage: "/wallet"